name: catech_inventory_routes
description: "Inventario + Optimización de Rutas (Flutter + Provider)"
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  file_picker: ^8.0.0
  url_launcher: ^6.3.0
  http: ^1.2.2
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # Performance optimizations
  tree-shake-icons: true
  # Enable web optimizations if building for web
  # web-renderer: html
